fixed bugs in mixed typography
SeedV/RTLTMPro pull request #2
Opened 2024-09-20 09:05 UTC by DearWWWWWT

2024-09-22 13:56 UTC, SeanNi1221 requested changes
1. 请将此 Repo 公开级别改为 SeedV private
2. 请将上级工程 ( splash-renderer-story ) 的集成修改一并提交 pull request
3. 以前之所以采用 submodule 方式集成, 是因为可以直接在上级工程中修改子模块并提交 pr, 若采用 git URL 方式集成, 鉴于 Assets 等基础资源已经在本 repo 中被删除,后续如何进行修改维护?

2024-09-22 14:09 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +﻿using System.Linq;
版权声明照此处理 (适用于所有文件):
1. 对于没有修改的原始文件, 保留原作者的版权声明不变
2. 对于新增的文件, 增加 SeedV 的版权声明
3. 对于修改的文件, 保留原作者的版权声明, 在下方增加 SeedV 的版权声明, 例如:
```
// <Original copyright statement by the previous author>
//
// The SeedV Lab (Beijing SeedV Technology Co., Ltd.) modifications: Copyright 2024 The SeedV Lab
// (Beijing SeedV Technology Co., Ltd.) All Rights Reserved. The modifications in this file are the intellectual property of the SeedV Lab.
```

2024-09-22 14:37 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/Types/MirroredCharsMaper.cs
> +      // ['«'] = '»',
- 如果非必要请删除
- 如果是有意保留, 注释写明保留的原因

2024-09-22 14:40 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +      //if no Arabic and English character is find, set to English
注释规则参考:
[非代码文本规范](https://seedvlab.feishu.cn/wiki/wikcn3rAB43mKMSdGDjDred3N9r#AaGjd22PtoiujQxVSxScIgCznzh) (审议中, 可共同探讨是否合理)

2024-09-22 14:41 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +      //if no Arabic and English character is find, set to English
```suggestion
      // If no Arabic and English character is find, set to English
```

2024-09-22 14:43 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +          // reserve for farther logic optimization
```suggestion
          // White Spaces don't affect text composing in the current logic.
          // Reserved for farther logic optimization.
```

2024-09-22 14:45 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +          // maybe a failed searching
```suggestion
          // Search backward for Context.Type.
          // May be a failed searching. 
```

2024-09-22 14:46 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +          // maybe a failed searching
```suggestion
          // Search forward for Context.Type.
          // May be a failed searching.
```

2024-09-22 14:57 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  //if right character is rightest, case previous type only
```suggestion
                  // If the current character is the last in the input, only consider the previous type.
```
我不确定是不是这个意思？

2024-09-22 14:58 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  //if previous type is default, there is no letter in or front this mirror character
```suggestion
                  // If the previous type is default, assume no letter exists before this character.
```

2024-09-22 14:59 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  //if all type is default, all text is not letter
```suggestion
                  // If both previous and next types are default, assume the text contains no letters.
```
不确定, 请核对

2024-09-22 15:01 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  if (i + j == input.Length - 1) behindType = mirrorPreviousType;
```suggestion
                  if (i + j == input.Length - 1) {
                    behindType = mirrorPreviousType;
                  }
```
A maximum of one statement per line. According to [C# at Google Style Guide](https://google.github.io/styleguide/csharp-style.html)

2024-09-22 15:02 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  if (mirrorPreviousType == ContextType.Default) mirrorPreviousType = mirrorBehindType;
```suggestion
                  if (mirrorPreviousType == ContextType.Default) {
                    mirrorPreviousType = mirrorBehindType;
                  }
```
A maximum of one statement per line. According to [C# at Google Style Guide](https://google.github.io/styleguide/csharp-style.html)

2024-09-22 15:03 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +          // in order to clearly see the judgment logic, ignore the grammar prompts here
```suggestion
          // In order to clearly see the judgment logic, ignore the grammar prompts here
```

2024-09-22 15:04 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +          // in order to clearly see the judgment logic, ignore the grammar prompts here
```suggestion
          // In order to clearly see the judgment logic, ignore the grammar prompts here
```

2024-09-22 15:04 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +          // in order to clearly see the judgment logic, ignore the grammar prompts here
```suggestion
          // In order to clearly see the judgment logic, ignore the grammar prompts here
```

2024-09-22 15:04 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +          // in order to clearly see the judgment logic, ignore the grammar prompts here
```suggestion
          // In order to clearly see the judgment logic, ignore the grammar prompts here
```

2024-09-22 15:09 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/Types/ContextType.cs
> +}
- Indentation of 2 spaces, no tabs.
- No line break before opening brace.

2024-09-23 09:03 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/FastStringBuilder.cs
请增加版权声明

2024-09-23 09:06 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +    private static readonly List<int> LtrTextHolder = new List<int>(512);
_ltrTextHolder

2024-09-23 09:06 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +    private static readonly List<int> TagTextHolder = new List<int>(512);
_tagTextHolder

2024-09-23 09:08 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +      MirroredCharsSet = new HashSet<char>(MirroredCharsMaper.MirroredCharsMap.Keys);
private static readonly HashSet<char> _mirroredCharsSet =
        new HashSet<char>(MirroredCharsMaper.MirroredCharsMap.Keys);
如果下一行是上一行的继续, 空4格, 不是2格

2024-09-23 09:17 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +    ///     Fixes the flow of the text.
对齐

2024-09-23 09:18 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +      // }
删除

2024-09-23 09:18 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +    public static void Fix(FastStringBuilder input, FastStringBuilder output, bool farsi, bool fixTextTags,
每行不超过100字

2024-09-23 09:19 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +      bool preserveNumbers) {
继续上一行空4格

2024-09-23 09:20 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +    private static readonly List<int> LtrTextHolder = new List<int>(512);
已修改

2024-09-23 09:20 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +    private static readonly List<int> TagTextHolder = new List<int>(512);
已修改

2024-09-23 09:21 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +      MirroredCharsSet = new HashSet<char>(MirroredCharsMaper.MirroredCharsMap.Keys);
已修改

2024-09-23 09:23 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +    public static void Fix(FastStringBuilder input, FastStringBuilder output, bool farsi, bool fixTextTags,
已修改

2024-09-23 09:23 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +    ///     Fixes the flow of the text.
已修改

2024-09-23 09:23 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +      // }
已修改

2024-09-23 09:24 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +      bool preserveNumbers) {
已修改

2024-09-23 09:28 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +            // so in this unit,Tag content's sequence is same with English
请重新调整, 或用中文书写

2024-09-23 09:28 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +                // other invalid condition also need consider
请重新调整, 或用中文书写

2024-09-23 09:29 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +              // this tag push process shuffle English text
请重新调整, 或用中文书写

2024-09-23 09:30 UTC, nistream commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +// (Beijing SeedV Technology Co., Ltd.) All Rights Reserved. The modifications in this file are the intellectual property of the SeedV Lab.
每行做多 100 字

2024-09-23 09:30 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +      ContextType[] isRtl = new ContextType[input.Length];
```suggestion
     var isRtl = new ContextType[input.Length];
```

2024-09-23 09:31 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +      // if no RightToLeft and LeftToRight character is find, set to LeftToRight
```suggestion
      // If no RightToLeft and LeftToRight character is found, set to LeftToRight
```

2024-09-23 09:31 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +        return (Enumerable.Repeat(ContextType.LeftToRight, input.Length).ToArray(), ContextType.LeftToRight);
每行最多 100 字

2024-09-23 09:32 UTC, nistream commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  // If the current character is the last in the input, only consider the previous type.
每行最多 100 字

2024-09-23 09:32 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  // If both previous and next types are default, assume the text contains no letters.
每行最多 100 字

2024-09-23 09:32 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  if (previousType == ContextType.LeftToRight && behindType == ContextType.LeftToRight &&
每行最多 100 字

2024-09-23 09:40 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +      // This list keeps the characters that their order should be reserved and streams reserved texts into final letters.
每行最多 100 字

2024-09-23 09:41 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +          // For cases where english words and farsi/arabic are mixed. This allows for using farsi/arabic, english and numbers in one sentence.
每行最多 100 字

2024-09-23 09:41 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +        if (Char32Utils.IsLetter(characterAtThisIndex) && !Char32Utils.IsRTLCharacter(characterAtThisIndex) ||
每行最多 100 字

2024-09-23 09:41 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +        // handle surrogates
```suggestion
        // Handle surrogates
```

2024-09-23 09:42 UTC, SeanNi1221 requested changes
As in comments.

2024-09-23 09:45 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                if (pairedPreviousType == ContextType.Default) pairedPreviousType = pairedBehindType;
每行最多 100 字

2024-09-23 09:45 UTC, nistream commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                if (previousType == ContextType.LeftToRight && behindType == ContextType.LeftToRight &&
每行最多 100 字

2024-09-23 09:49 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/Types/MirroredCharsMaper.cs
> +// The SeedV Lab (Beijing SeedV Technology Co., Ltd.) modifications: Copyright 2024 The SeedV Lab
每行最多 100 字

2024-09-23 09:50 UTC, SeanNi1221 commented on UPMPackage/Scripts/Runtime/Types/ContextType.cs
> +// (Beijing SeedV Technology Co., Ltd.) All Rights Reserved.
每行最多 100 字

2024-09-23 10:05 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +            // so in this unit,Tag content's sequence is same with English
已调整

2024-09-23 10:05 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +                // other invalid condition also need consider
已调整

2024-09-23 10:17 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/Types/ContextType.cs
> +// (Beijing SeedV Technology Co., Ltd.) All Rights Reserved.
已修改

2024-09-23 10:17 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/Types/MirroredCharsMaper.cs
> +// The SeedV Lab (Beijing SeedV Technology Co., Ltd.) modifications: Copyright 2024 The SeedV Lab
已修改

2024-09-23 10:17 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                if (previousType == ContextType.LeftToRight && behindType == ContextType.LeftToRight &&
已修改

2024-09-23 10:17 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                if (pairedPreviousType == ContextType.Default) pairedPreviousType = pairedBehindType;
已修改

2024-09-23 10:19 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +        // handle surrogates
已修改

2024-09-23 10:19 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +        if (Char32Utils.IsLetter(characterAtThisIndex) && !Char32Utils.IsRTLCharacter(characterAtThisIndex) ||
已修改

2024-09-23 10:19 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +          // For cases where english words and farsi/arabic are mixed. This allows for using farsi/arabic, english and numbers in one sentence.
已修改

2024-09-23 10:19 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +      // This list keeps the characters that their order should be reserved and streams reserved texts into final letters.
已修改

2024-09-23 10:19 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  if (previousType == ContextType.LeftToRight && behindType == ContextType.LeftToRight &&
已修改

2024-09-23 10:19 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  // If both previous and next types are default, assume the text contains no letters.
已修改

2024-09-23 10:19 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +                  // If the current character is the last in the input, only consider the previous type.
已修改

2024-09-23 10:19 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +        return (Enumerable.Repeat(ContextType.LeftToRight, input.Length).ToArray(), ContextType.LeftToRight);
已修改

2024-09-23 10:19 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +      // if no RightToLeft and LeftToRight character is find, set to LeftToRight
已修改

2024-09-23 10:19 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +      ContextType[] isRtl = new ContextType[input.Length];
已修改

2024-09-23 10:20 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/MixedTypographer.cs
> +// (Beijing SeedV Technology Co., Ltd.) All Rights Reserved. The modifications in this file are the intellectual property of the SeedV Lab.
已修改

2024-09-23 10:20 UTC, DearWWWWWT commented on UPMPackage/Scripts/Runtime/LigatureFixer.cs
> +              // this tag push process shuffle English text
已修改

2024-09-23 10:23 UTC, DearWWWWWT commented
已删除版权声明

2024-09-23 10:27 UTC, SeanNi1221 approved these changes
LGTM

2024-09-23 10:28 UTC, merged